export enum PAGES {
    IDENTIFY_PLANT= 'IDENTIFY_PLANT',
    RECOGNIZE= 'RECOGNIZE',
    LEARN_TOXIC= 'LEARN_TOXIC',
    DIAGNOSE_PLANT= 'DIAGNOSE_PLANT',
    PLANT_CARE= 'PLANT_CARE',
    MAKE_EASY= 'MAKE_EASY',
    REGISTRATION= 'REGISTRATION',
}
